UNIT_NAME := LightController
PRJ_ROOT  := ../../..

#
# srcディレクトリからの相対パスでテストするソースコードを列挙する.
#
SRC := HomeAutomation/LightController.c

#
# カレントディレクトリからの相対パスでテストコードを列挙する.
#
TEST_CODE := LightControllerTest.cpp

#
# mockディレクトリからの相対パスでモックコードを列挙する.
#
MOCK_CODE := Device/MockLightDriver.cpp

include $(PRJ_ROOT)/framework/mk/MakefileWorker.mk
