UNIT_NAME := RandomMinute
PRJ_ROOT  := ../../../..

#
# srcディレクトリからの相対パスでテストするソースコードを列挙する.
#
SRC := HomeAutomation/RandomMinute.c

#
# カレントディレクトリからの相対パスでテストコードを列挙する.
#
TEST_CODE := RandomMinuteTest.cpp

#
# mockディレクトリからの相対パスでモックコードを列挙する.
#
MOCK_CODE :=

include $(PRJ_ROOT)/framework/mk/MakefileWorker.mk
