UNIT_NAME := Flash
PRJ_ROOT  := ../../..

#
# srcディレクトリからの相対パスでテストするソースコードを列挙する.
#
SRC := IO/Flash.c

#
# カレントディレクトリからの相対パスでテストコードを列挙する.
#
TEST_CODE := FlashTest.cpp

#
# mockディレクトリからの相対パスでモックコードを列挙する.
#
MOCK_CODE := IO/MockIO.cpp IO/MockMicroTime.cpp

include $(PRJ_ROOT)/framework/MakefileWorker.mk
