UNIT_NAME := CircularBuffer

PRODUCT_CODE_DIR := ../../../source
UTEST_FRAMEWORK_HOME := ../../../framework

# PRODUCT_CODE_DIRからの相対パスでテストするソースコードを列挙する
SOURCES := util/CircularBuffer.c

TEST_CODE_DIRS := .

MOCK_CODE_DIRS :=

INCLUDE_DIRS = ../../../include

include $(UTEST_FRAMEWORK_HOME)/MakefileWorker.mk
