UNIT_NAME := CircularBuffer
PRJ_ROOT  := ../../..

#
# srcディレクトリからの相対パスでテストするソースコードを列挙する.
#
SRC := util/CircularBuffer.c \
       util/Utils.c

#
# カレントディレクトリからの相対パスでテストコードを列挙する.
#
TEST_CODE := CircularBufferTest.cpp

#
# mockディレクトリからの相対パスでモックコードを列挙する.
#
MOCK_CODE :=

include $(PRJ_ROOT)/framework/mk/MakefileWorker.mk
