UNIT_NAME := CircularBuffer
PRJ_ROOT  := ../../..

# PRODUCT_CODE_DIRからの相対パスでテストするソースコードを列挙する
SRC := util/CircularBuffer.c

TEST_CODE_DIR := .

MOCK_CODE_DIR :=

include $(PRJ_ROOT)/framework/MakefileWorker.mk
