UNIT_NAME := LedDriver
PRJ_ROOT  := ../..

#
# srcディレクトリからの相対:パスでテストするソースコードを列挙する.
#
SRC := LedDriver/LedDriver.c

#
# カレントディレクトリからの相対パスでテストコードを列挙する.
#
TEST_CODE := LedDriverTest.cpp

#
# mockディレクトリからの相対パスでモックコードを列挙する.
#
MOCK_CODE := util/MockRuntimeError.cpp

include $(PRJ_ROOT)/framework/MakefileWorker.mk
